version: "3.7"

services:
  biomultitool:
    build:
      dockerfile: dockerfile-backend
      context: ./backend
    depends_on:
      - db
    tty: true
    ports:
      - 8080:8080
    volumes:
      - shared:/shared
    networks:
      bmt:

  worker:
    build:
      dockerfile: dockerfile-worker
      context: ./worker
    depends_on:
      - db
    environment:
      - THREAD_CONCURRENCY=4
      - WORKER_CORES=2
      - POOL_SIZE=32
      - POLLING_RATE=5000
    tty: true
    volumes:
      - shared:/shared
    networks:
      bmt:

  db:
    image: mongo
    volumes:
      - db:/data/db
    networks:
      bmt:
        aliases:
          - db

volumes:
  db:
  shared:

networks:
  bmt:
